"""Interfaces (Protocol) del Repository Pattern.

Las implementaciones concretas viven en app.infrastructure.repositories.
Se tipan contra los modelos ORM para evitar duplicar entidades (ver
docs/decisiones.md: se descarta una capa extra de entidades de dominio
puras por sobreingeniería para el tamaño de este proyecto).
"""

from datetime import date
from typing import Protocol
from uuid import UUID

from app.domain.enums import EstadoOrdenTrabajo, RolUsuario, TipoOrdenTrabajo
from app.infrastructure.db.models import (
    Administracion,
    Ascensor,
    Cliente,
    Edificio,
    Emergencia,
    OrdenTrabajo,
    Papeleta,
    PapeletaItem,
    PautaMantencion,
    PiezaReemplazada,
    Usuario,
)


class ClienteRepository(Protocol):
    async def listar(self, limit: int, offset: int) -> tuple[list[Cliente], int]: ...
    async def obtener(self, id_: UUID) -> Cliente | None: ...
    async def crear(self, cliente: Cliente) -> Cliente: ...
    async def administraciones(self, cliente_id: UUID) -> list[Administracion]: ...


class AdministracionRepository(Protocol):
    async def listar(self, limit: int, offset: int) -> tuple[list[Administracion], int]: ...
    async def obtener(self, id_: UUID) -> Administracion | None: ...
    async def crear(self, administracion: Administracion) -> Administracion: ...
    async def edificios(self, administracion_id: UUID) -> list[Edificio]: ...


class EdificioRepository(Protocol):
    async def listar(
        self, limit: int, offset: int, administracion_id: UUID | None
    ) -> tuple[list[Edificio], int]: ...
    async def obtener(self, id_: UUID) -> Edificio | None: ...
    async def crear(self, edificio: Edificio) -> Edificio: ...


class AscensorRepository(Protocol):
    async def listar(
        self, limit: int, offset: int, edificio_id: UUID | None
    ) -> tuple[list[Ascensor], int]: ...
    async def obtener(self, id_: UUID) -> Ascensor | None: ...
    async def crear(self, ascensor: Ascensor) -> Ascensor: ...
    async def bitacora(self, ascensor_id: UUID) -> list[OrdenTrabajo]: ...


class UsuarioRepository(Protocol):
    async def listar(
        self, limit: int, offset: int, rol: RolUsuario | None
    ) -> tuple[list[Usuario], int]: ...
    async def obtener(self, id_: UUID) -> Usuario | None: ...
    async def crear(self, usuario: Usuario) -> Usuario: ...


class PautaRepository(Protocol):
    async def listar(self, limit: int, offset: int) -> tuple[list[PautaMantencion], int]: ...
    async def obtener(self, id_: UUID) -> PautaMantencion | None: ...
    async def crear(self, pauta: PautaMantencion) -> PautaMantencion: ...


class EmergenciaRepository(Protocol):
    async def listar(
        self, limit: int, offset: int, estado: str | None
    ) -> tuple[list[Emergencia], int]: ...
    async def obtener(self, id_: UUID) -> Emergencia | None: ...
    async def crear(self, emergencia: Emergencia) -> Emergencia: ...
    async def guardar(self, emergencia: Emergencia) -> Emergencia: ...
    async def siguiente_codigo(self) -> str: ...


class OrdenTrabajoRepository(Protocol):
    async def listar(
        self,
        limit: int,
        offset: int,
        desde: date | None,
        hasta: date | None,
        tecnico_id: UUID | None,
        estado: EstadoOrdenTrabajo | None,
        tipo: TipoOrdenTrabajo | None,
        edificio_id: UUID | None,
    ) -> tuple[list[OrdenTrabajo], int]: ...
    async def obtener(self, id_: UUID) -> OrdenTrabajo | None: ...
    async def crear(self, orden: OrdenTrabajo) -> OrdenTrabajo: ...
    async def guardar(self, orden: OrdenTrabajo) -> OrdenTrabajo: ...
    async def siguiente_codigo(self) -> str: ...
    async def listar_por_mes(self, anio: int, mes: int) -> list[OrdenTrabajo]: ...


class PapeletaRepository(Protocol):
    async def obtener(self, id_: UUID) -> Papeleta | None: ...
    async def obtener_por_orden(self, orden_trabajo_id: UUID) -> Papeleta | None: ...
    async def crear(self, papeleta: Papeleta) -> Papeleta: ...
    async def guardar(self, papeleta: Papeleta) -> Papeleta: ...
    async def obtener_item(self, item_id: UUID) -> PapeletaItem | None: ...
    async def guardar_item(self, item: PapeletaItem) -> PapeletaItem: ...
    async def agregar_pieza(self, pieza: PiezaReemplazada) -> Papeleta: ...
    async def eliminar_pieza(self, papeleta_id: UUID, pieza_id: UUID) -> Papeleta: ...
