"""Interfaces (Protocol) del Repository Pattern.

Las implementaciones concretas viven en app.infrastructure.repositories.
Se tipan contra los modelos ORM para evitar duplicar entidades (ver
docs/decisiones.md: se descarta una capa extra de entidades de dominio
puras por sobreingeniería para el tamaño de este proyecto).
"""

from datetime import date
from typing import Protocol
from uuid import UUID

from app.domain.enums import EstadoOrdenTrabajo, RolUsuario, TipoOrdenTrabajo
from app.infrastructure.db.models import (
    Ascensor,
    Edificio,
    OrdenTrabajo,
    Papeleta,
    PapeletaChecklistItem,
    PautaMantencion,
    Usuario,
)


class EdificioRepository(Protocol):
    async def listar(self, limit: int, offset: int) -> tuple[list[Edificio], int]: ...
    async def obtener(self, id_: UUID) -> Edificio | None: ...
    async def crear(self, edificio: Edificio) -> Edificio: ...


class AscensorRepository(Protocol):
    async def listar(
        self, limit: int, offset: int, edificio_id: UUID | None
    ) -> tuple[list[Ascensor], int]: ...
    async def obtener(self, id_: UUID) -> Ascensor | None: ...
    async def crear(self, ascensor: Ascensor) -> Ascensor: ...


class UsuarioRepository(Protocol):
    async def listar(
        self, limit: int, offset: int, rol: RolUsuario | None
    ) -> tuple[list[Usuario], int]: ...
    async def obtener(self, id_: UUID) -> Usuario | None: ...
    async def crear(self, usuario: Usuario) -> Usuario: ...


class PautaRepository(Protocol):
    async def listar(self, limit: int, offset: int) -> tuple[list[PautaMantencion], int]: ...
    async def obtener(self, id_: UUID) -> PautaMantencion | None: ...
    async def crear(self, pauta: PautaMantencion) -> PautaMantencion: ...


class OrdenTrabajoRepository(Protocol):
    async def listar(
        self,
        limit: int,
        offset: int,
        desde: date | None,
        hasta: date | None,
        tecnico_id: UUID | None,
        estado: EstadoOrdenTrabajo | None,
        tipo: TipoOrdenTrabajo | None,
        edificio_id: UUID | None,
    ) -> tuple[list[OrdenTrabajo], int]: ...
    async def obtener(self, id_: UUID) -> OrdenTrabajo | None: ...
    async def crear(self, orden: OrdenTrabajo) -> OrdenTrabajo: ...
    async def guardar(self, orden: OrdenTrabajo) -> OrdenTrabajo: ...
    async def siguiente_codigo(self) -> str: ...
    async def listar_por_mes(self, anio: int, mes: int) -> list[OrdenTrabajo]: ...


class PapeletaRepository(Protocol):
    async def obtener(self, id_: UUID) -> Papeleta | None: ...
    async def obtener_por_orden(self, orden_trabajo_id: UUID) -> Papeleta | None: ...
    async def crear(self, papeleta: Papeleta) -> Papeleta: ...
    async def guardar(self, papeleta: Papeleta) -> Papeleta: ...
    async def obtener_item(self, item_id: UUID) -> PapeletaChecklistItem | None: ...
    async def guardar_item(self, item: PapeletaChecklistItem) -> PapeletaChecklistItem: ...
